Repository AlexandreVolts/my-social-network, pull requests merged in 2023-08, with the labels that each got.

#1 feat(app):added button component
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  ROADMAP.md
  UPDATES.md
  package.json
  src/components/ui/Button.tsx
  src/stories/Button.stories.tsx
  src/stories/Button.tsx
  src/stories/Header.tsx
  src/stories/button.css
  yarn.lock
Labels: enhancement

#2 feat(ui):added text input component
  ROADMAP.md
  UPDATES.md
  src/components/ui/Button.tsx
  src/components/ui/TextInput.tsx
  src/stories/Button.stories.tsx
  src/stories/TextInput.stories.tsx
  yarn.lock
Labels: enhancement

#4 feat(ui):added simple card component
  UPDATES.md
  src/components/ui/Card.tsx
  src/components/ui/TextInput.tsx
  src/stories/Card.stories.tsx
Labels: enhancement

#5 feat(ui):added a select component
  ROADMAP.md
  UPDATES.md
  src/components/ui/Select.tsx
  src/components/ui/TextInput.tsx
  src/stories/Select.stories.tsx
Labels: enhancement

#6 feat(ui):added datepicker component
  ROADMAP.md
  UPDATES.md
  src/components/ui/DatePicker.tsx
  src/stories/DatePicker.stories.tsx
Labels: enhancement

#7 Fix/input icon focus
  src/components/ui/DatePicker.tsx
  src/components/ui/TextInput.tsx
Labels: enhancement

#8 Feature/register form
  ROADMAP.md
  UPDATES.md
  package.json
  src/app/types/RegisterFormData.ts
  src/components/RegisterForm.tsx
  src/components/ui/TextInput.tsx
  src/stories/RegisterForm.stories.tsx
  yarn.lock
Labels: enhancement

#11 fix(datepicker): fixed month display
  ROADMAP.md
  src/components/ui/DatePicker.tsx
Labels: enhancement

#10 feat(app): reconfigured i18n with storybook
  .storybook/preview.ts
  .storybook/preview.tsx
  ROADMAP.md
  i18n.ts
  next.config.js
  src/app/[locale]/layout.tsx
  src/app/[locale]/page.tsx
Labels: enhancement

#12 feat(ui): Overlay component created; Select component updated
  ROADMAP.md
  UPDATES.md
  src/components/ui/Overlay.tsx
  src/components/ui/Select.tsx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Overlay.stories.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/header.css
  src/stories/page.css
Labels: enhancement

#13 feat(app): Header component
  ROADMAP.md
  UPDATES.md
  src/components/Header.tsx
  src/stories/Header.stories.tsx
Labels: enhancement

#14 feat(about): About page
  ROADMAP.md
  UPDATES.md
  src/app/[locale]/about/page.tsx
Labels: enhancement

#15 Feature/form implementation
  messages/en.json
  messages/eo.json
  messages/es.json
  messages/fr.json
  src/app/[locale]/page.tsx
  src/components/LoginForm.tsx
  src/components/RegisterForm.tsx
  src/components/ui/Button.tsx
  src/components/ui/DatePicker.tsx
  src/components/ui/Select.tsx
  src/components/ui/TextInput.tsx
  src/stories/LoginForm.stories.tsx
  src/stories/RegisterForm.stories.tsx
Labels: enhancement

#16 feat(ui): Added whileTap animation
  ROADMAP.md
  UPDATES.md
  src/components/ui/Button.tsx
  src/components/ui/TextInput.tsx
Labels: ui

#17 feat(app):added footer component
  ROADMAP.md
  UPDATES.md
  messages/en.json
  messages/eo.json
  messages/es.json
  messages/fr.json
  public/esperanto.png
  src/app/[locale]/about/page.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/LanguageSwitcher.tsx
  src/components/ui/DatePicker.tsx
  src/components/ui/Select.tsx
  src/stories/Footer.stories.tsx
  src/stories/Select.stories.tsx
Labels: enhancement

#18 Feature/log reg pages
  ROADMAP.md
  UPDATES.md
  src/app/[locale]/login/page.tsx
  src/app/[locale]/register/page.tsx
Labels: enhancement

#21 fix(loginform): implemented email-type errors & error display updates
  ROADMAP.md
  UPDATES.md
  src/components/LoginForm.tsx
Labels: enhancement

#23 fix(app): Type folder moved
  src/app/[locale]/page.tsx
  src/components/LoginForm.tsx
  src/hooks/useLogin.ts
  src/types/LoginFormData.tsx
  src/types/RegisterFormData.ts
Labels: bug

#22 Feature/button icons
  ROADMAP.md
  UPDATES.md
  src/app/[locale]/login/page.tsx
  src/app/[locale]/page.tsx
  src/app/[locale]/register/page.tsx
  src/components/LoginForm.tsx
  src/components/RegisterForm.tsx
  src/components/ui/Loader.tsx
  src/hooks/useLogin.ts
  src/stories/Loader.stories.tsx
  src/stories/LoginForm.stories.tsx
  src/stories/RegisterForm.stories.tsx
Labels: enhancement

#24 feat(ui):added avatar component
  src/components/ui/Avatar.tsx
  src/stories/Avatar.stories.tsx
Labels: ui

#25 feat(ui): TextArea component made
  ROADMAP.md
  UPDATES.md
  src/components/ui/TextArea.tsx
  src/components/ui/TextInput.tsx
  src/stories/TextArea.stories.tsx
  src/stories/TextInput.stories.tsx
  src/types/BaseInputProps.tsx
Labels: ui

#27 feat(app):added post card component
  .storybook/main.ts
  ROADMAP.md
  messages/en.json
  messages/eo.json
  messages/es.json
  messages/fr.json
  src/components/PostCard.tsx
  src/components/ui/ActionIcon.tsx
  src/hooks/useElapsedDelayFormat.ts
  src/stories/ActionIcon.stories.tsx
  src/stories/PostCard.stories.tsx
Labels: enhancement

#26 feat(app): Home page created
  ROADMAP.md
  UPDATES.md
  messages/en.json
  messages/eo.json
  messages/es.json
  messages/fr.json
  src/app/[locale]/home/page.tsx
  src/components/LoginForm.tsx
  src/components/PublishModal.tsx
  src/components/RegisterForm.tsx
  src/components/ui/Button.tsx
  src/components/ui/Card.tsx
  src/components/ui/Modal.tsx
  src/components/ui/Overlay.tsx
  src/components/ui/TextArea.tsx
  src/components/ui/TextInput.tsx
  src/stories/PublishModal.stories.tsx
Labels: enhancement

#28 Feature/create posts with supabase
  ROADMAP.md
  UPDATES.md
  src/app/[locale]/home/page.tsx
  src/components/ui/Modal.tsx
  src/components/ui/Overlay.tsx
  src/hooks/useUser.ts
Labels: enhancement

#30 Feature/comment component
  ROADMAP.md
  UPDATES.md
  src/components/CommentCard.tsx
  src/components/PostCard.tsx
  src/components/ui/ReadMoreText.tsx
  src/hooks/useElapsedDelayFormat.ts
  src/stories/CommentCard.stories.tsx
  src/stories/ReadMoreText.stories.tsx
  src/types/BasePublishedContentProps.tsx
Labels: enhancement

#29 Feature/supabase guard system
  src/app/[locale]/about/page.tsx
  src/app/[locale]/home/page.tsx
  src/app/[locale]/login/page.tsx
  src/app/[locale]/page.tsx
  src/app/[locale]/register/page.tsx
  src/components/Header.tsx
  src/components/ui/Overlay.tsx
  src/components/ui/Select.tsx
  src/hooks/useLogin.ts
  src/hooks/useUser.ts
  src/stories/Header.stories.tsx
Labels: enhancement

#31 feat(ui): Dropdown component made
  ROADMAP.md
  UPDATES.md
  src/components/ui/Dropdown.tsx
  src/components/ui/Modal.tsx
  src/stories/Dropdown.stories.tsx
Labels: ui

#32 Feature/compound post
  src/components/CommentCard.tsx
  src/components/PostCard.tsx
  src/stories/PostCard.stories.tsx
  src/types/BasePublishedContentProps.tsx
Labels: enhancement

#34 Feature/home page post display
  ROADMAP.md
  UPDATES.md
  src/app/[locale]/home/page.tsx
  src/components/PostCard.tsx
  src/types/PostProps.tsx
  src/utils/getPosts.ts
Labels: enhancement

#33 Feature/post author actions
  ROADMAP.md
  UPDATES.md
  messages/en.json
  messages/eo.json
  messages/es.json
  messages/fr.json
  src/components/CommentCard.tsx
  src/components/PostCard.tsx
  src/components/ui/ActionIcon.tsx
  src/components/ui/Dropdown.tsx
  src/types/BasePublishedContentProps.tsx
Labels: enhancement

#35 feat(ui):toaster-component
  ROADMAP.md
  UPDATES.md
  src/components/ui/Toaster.tsx
  src/stories/Toaster.stories.tsx
Labels: ui

#36 feat(app):small fixes, click propagation handling & click on post tog…
  ROADMAP.md
  UPDATES.md
  src/app/[locale]/home/page.tsx
  src/components/CommentCard.tsx
  src/components/PostCard.tsx
  src/components/ui/ActionIcon.tsx
  src/components/ui/Dropdown.tsx
  src/stories/Card.stories.tsx
  src/stories/CommentCard.stories.tsx
  src/stories/PostCard.stories.tsx
Labels: enhancement

#37 feat(app):implemented post deletion system & supabase file
  UPDATES.md
  messages/en.json
  messages/eo.json
  messages/es.json
  messages/fr.json
  src/app/[locale]/home/page.tsx
  src/components/PostCard.tsx
  src/components/ui/Dropdown.tsx
  src/components/ui/Toaster.tsx
  src/types/PostProps.tsx
  src/utils/supabase.ts
Labels: enhancement

#38 Feature/post likes
  ROADMAP.md
  UPDATES.md
  src/app/[locale]/home/page.tsx
  src/components/PostCard.tsx
  src/components/ui/LikeIcon.tsx
  src/stories/LikeIcon.stories.tsx
  src/types/BasePublishedContentProps.tsx
  src/types/LikeProps.ts
  src/utils/supabase.ts
Labels: enhancement

#39 Feature/manage publication
  UPDATES.md
  src/app/[locale]/home/page.tsx
  src/components/PostCard.tsx
  src/hooks/useQuery.ts
  src/utils/supabase.ts
Labels: enhancement

#41 Feature/profile page
  ROADMAP.md
  UPDATES.md
  messages/en.json
  messages/eo.json
  messages/es.json
  messages/fr.json
  src/app/[locale]/home/page.tsx
  src/app/[locale]/profile/[userid]/page.tsx
  src/types/UserData.tsx
  src/utils/supabase.ts
Labels: enhancement

#40 feat(posts): Posts can now be edited.
  ROADMAP.md
  UPDATES.md
  messages/en.json
  messages/eo.json
  messages/es.json
  messages/fr.json
  src/app/[locale]/home/page.tsx
  src/app/[locale]/layout.tsx
  src/components/CreatePostCard.tsx
  src/components/PostCard.tsx
  src/components/PublishModal.tsx
  src/components/ui/ActionIcon.tsx
  src/components/ui/LikeIcon.tsx
  src/components/ui/Overlay.tsx
  src/components/ui/TextArea.tsx
  src/hooks/useRestQuery.ts
  src/stories/CreateNewPost.stories.tsx
  src/stories/PublishModal.stories.tsx
  src/types/BasePublishedContentProps.tsx
  src/types/PostProps.tsx
  src/utils/supabase.ts
Labels: enhancement

#43 Feature/fix build
  src/components/CommentCard.tsx
  src/hooks/useRestQuery.ts
  src/stories/CommentCard.stories.tsx
  src/stories/CreateNewPost.stories.tsx
  src/stories/PostCard.stories.tsx
  src/stories/PublishModal.stories.tsx
Labels: bug

#44 Feature/follow system
  ROADMAP.md
  UPDATES.md
  messages/en.json
  messages/eo.json
  messages/es.json
  messages/fr.json
  src/app/[locale]/profile/[userid]/page.tsx
  src/components/UserListModal.tsx
  src/components/ui/Button.tsx
  src/hooks/useRestQuery.ts
  src/stories/UserListModal.stories.tsx
  src/types/FollowProps.tsx
  src/types/PostProps.tsx
  src/types/UserData.tsx
  src/utils/supabase.ts
Labels: enhancement

#45 Feature/pin component
  ROADMAP.md
  UPDATES.md
  src/components/ui/Pin.tsx
  src/stories/Pin.stories.tsx
Labels: ui
